# Generated by Django 3.1.4 on 2020-12-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20201210_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
    ]
