# Generated by Django 3.1.4 on 2020-12-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_enlace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='enlace',
            new_name='link',
        ),
    ]
